var menudata={children:[
{text:"Página Principal",url:"index.html"},
{text:"Estruturas de Dados",url:"annotated.html",children:[
{text:"Estruturas de Dados",url:"annotated.html"},
{text:"Índice das Estruturas de Dados",url:"classes.html"},
{text:"Campos de Dados",url:"functions.html",children:[
{text:"Todos",url:"functions.html"},
{text:"Variáveis",url:"functions_vars.html"}]}]},
{text:"Arquivos",url:"files.html",children:[
{text:"Lista de Arquivos",url:"files.html"},
{text:"Globais",url:"globals.html",children:[
{text:"Todos",url:"globals.html",children:[
{text:"a",url:"globals.html#index_a"},
{text:"b",url:"globals.html#index_b"},
{text:"c",url:"globals.html#index_c"},
{text:"d",url:"globals.html#index_d"},
{text:"e",url:"globals.html#index_e"},
{text:"f",url:"globals.html#index_f"},
{text:"g",url:"globals.html#index_g"},
{text:"i",url:"globals.html#index_i"},
{text:"l",url:"globals.html#index_l"},
{text:"m",url:"globals.html#index_m"},
{text:"n",url:"globals.html#index_n"},
{text:"p",url:"globals.html#index_p"},
{text:"r",url:"globals.html#index_r"},
{text:"s",url:"globals.html#index_s"},
{text:"t",url:"globals.html#index_t"},
{text:"v",url:"globals.html#index_v"},
{text:"w",url:"globals.html#index_w"}]},
{text:"Funções",url:"globals_func.html",children:[
{text:"a",url:"globals_func.html#index_a"},
{text:"c",url:"globals_func.html#index_c"},
{text:"f",url:"globals_func.html#index_f"},
{text:"g",url:"globals_func.html#index_g"},
{text:"i",url:"globals_func.html#index_i"},
{text:"l",url:"globals_func.html#index_l"},
{text:"m",url:"globals_func.html#index_m"},
{text:"p",url:"globals_func.html#index_p"},
{text:"r",url:"globals_func.html#index_r"},
{text:"s",url:"globals_func.html#index_s"}]},
{text:"Variáveis",url:"globals_vars.html"},
{text:"Definições de Tipos",url:"globals_type.html"},
{text:"Enumerações",url:"globals_enum.html"},
{text:"Valores de enumerações",url:"globals_eval.html"},
{text:"Definições e Macros",url:"globals_defs.html"}]}]}]}
